version: "3"

services: 
    app:
        image: klakegg/hugo:alpine
        command: server
        volumes:
            - "./src:/src"
        ports:
            - "1313:1313"
        environment: 
            HUGO_PARAMS_baseUrl: ""