languageCode = "en-us"

title = "UKnowWhoIm"
theme = "hugo-coder"

[params]
author = "Sidharth Ajithkumar"
info = "Software Engineer | Web Developer"
description = "My personal website"
keywords = "developer,personal"
#avatarurl = "images/avatar.jpg"
colorScheme = "dark"
favicon_32 = "/img/favicon-32x32.png"
favicon_16 = "/img/favicon-16x16.png"
customCSS = ["css/extra.css"]
customJS = ["js/script.js"]

hideFooter = false
hideCredits = false
hideCopyright = false

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/UKnowWhoIm/"

[[params.social]]
name = "Email"
icon = "fa fa-envelope"
weight = 3
url = "mailto:sidharthajithkumar@gmail.com"


[[params.social]]
name = "LinkedIn"
icon = "fa fa-linkedin"
weight = 2
url = "https://www.linkedin.com/in/uknowwhoim/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Skills"
weight = 2
url = "skills/"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Work Experience"
weight = 4
url = "work-experience/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
